#!/bin/sh

TZ=tz
HOST=localhost
PORT=1234

FILE1=/tmp/tz1-$$
FILE2=/tmp/tz2-$$
ERROR=/tmp/tz-err-$$

GETTEXT="gettext -d tz_ui"

if [ -r ~/.tz.conf ]
then
	. ~/.tz.conf
elif [ -r /etc/tz.conf ]
then
	. /etc/tz.conf
fi

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=gdialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi

if [ $# -ge 1 -o `basename $0` = 'ntz_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        TZ="nc $HOST $PORT"
	else
		echo "You must set HOST and PORT"
		exit -2
	fi
fi

while true
do
	$DIALOG --inputbox "`$GETTEXT \"Enter location (Continent-City):\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $TZ > $FILE2 2>$ERROR
	then
		MSG="`$GETTEXT \"Date:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
