#!/bin/sh

TZ=tz
HOST=localhost
PORT=1234

FILE1=/tmp/tz1-$$
FILE2=/tmp/tz2-$$
ERROR=/tmp/tz-err-$$

GETTEXT="gettext -d tz_ui"


which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=gdialog


end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}


while true
do
	$DIALOG --inputbox "`$GETTEXT \"Enter location (Continent-City):\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | $TZ > $FILE2 2>$ERROR
	then
		MSG="`$GETTEXT \"Date:\"` `cat $FILE2`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 7 20 || end
	else
		MSG="`$GETTEXT \"Error:\"`\\n\\n`cat $ERROR`\\n\\n`$GETTEXT \"Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done
